### GERAL

In [3]:
import numpy as np

In [32]:
np.zeros(5)
# equivale ao .ones()

array([0., 0., 0., 0., 0.])

In [36]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [31]:
np.arange(1,5+1)

array([1, 2, 3, 4, 5])

In [30]:
np.linspace(1,2,5)
# São distribuidos linearmente
# Param em X, não em X+1

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [22]:
np.eye(5)
# Matriz de identidade 

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### RANDOM

In [28]:
np.random.rand(5)
# Números aleatórios entre 0 e 1

array([0.40836176, 0.47761799, 0.64454061, 0.1544088 , 0.23743176])

In [29]:
np.random.randn(5)
# Números aleatórios em uma distribuição normal

array([-0.60525172,  1.1396121 ,  0.08203038, -0.94496467,  0.16662607])

In [81]:
np.random.randint(1,100+1,5)
# np.random.randint(1,100+1)

array([60, 37, 60,  4, 54])

### SHAPE

In [29]:
arr.shape

(4, 9)

### RESHAPE

In [31]:
arr = np.arange(1,36+1)
arr = arr.reshape(4,9)
arr

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34, 35, 36]])

### SHAPE

In [32]:
arr.shape

(4, 9)

### INDEXING

In [5]:
arr = np.arange(1,25+1).reshape(5,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [41]:
arr[2:4,1:4]

array([[20, 21, 22],
       [29, 30, 31]])

In [43]:
arr[[2,0,1,3]]

array([[19, 20, 21, 22, 23, 24, 25, 26, 27],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18],
       [28, 29, 30, 31, 32, 33, 34, 35, 36]])

In [49]:
arr1d = arr[0]
arr1d

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [51]:
arr1d > 4

array([False, False, False, False,  True,  True,  True,  True,  True])

In [52]:
arr1d[arr1d > 4]

array([5, 6, 7, 8, 9])

### OPERATIONS

In [53]:
arr1d

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [58]:
arr1d+arr1d
#(+) (-) (*) (/) (%) (**n)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [59]:
np.sqrt(arr1d)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        ])

In [61]:
np.exp(arr1d)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03])

In [67]:
np.log(arr1d)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [66]:
np.sin(arr1d)
#(cos) (tan)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

### MAX MIN

In [68]:
arr = np.asarray([32, 68, 67, 25, 30, 77, 66, 37])

In [17]:
array.max()

77

In [18]:
array.min()

25

In [19]:
array.argmax()

5

In [20]:
array.argmin()

3